# SOFA Pipeline Configuration
# This file contains environment-specific settings for the pipeline workflow

# Cache settings
cache:
  # Cache SOFA binaries to avoid re-downloading
  sofa_binaries:
    enabled: true
    ttl_days: 7
    
  # Cache Python dependencies
  python_deps:
    enabled: true
    ttl_days: 1
    
  # Cache intermediate data files
  pipeline_data:
    enabled: true
    ttl_hours: 6

# Pipeline settings
pipeline:
  # Default stage to run if not specified
  default_stage: "all"
  
  # Timeout for each stage (in minutes)
  stage_timeouts:
    gather: 30
    fetch: 45  
    build: 60
    
  # Retry configuration
  retries:
    max_attempts: 3
    backoff_minutes: 5

# RSS generation settings  
rss:
  # Default RSS generation preference
  generate_by_default: true
  
  # RSS feed configuration
  title: "SOFA - Apple Software Updates"
  description: "Simple Organized Feed for Apple Software Updates by Mac Admins"
  link: "https://sofa-beta.macadmin.me"
  
  # Output settings
  output_file: "data/feeds/v1/rss_feed.xml"
  retention_days: 30

# Commit settings
commit:
  # Auto-commit pipeline results
  auto_commit: true
  
  # Commit message template
  message_template: |
    Update SOFA data pipeline results
    
    - Pipeline stage: {stage}
    - SOFA CLI version: {version}
    - Generated at: {timestamp}
    - RSS feeds: {rss_status}

# Monitoring and notifications
monitoring:
  # Create detailed job summaries
  detailed_summaries: true
  
  # Upload artifacts for debugging
  upload_artifacts: true
  artifact_retention_days: 7

# Security settings
security:
  # Use GitHub's GITHUB_TOKEN
  use_github_token: true
  
  # Restrict pipeline to main branch
  branch_protection: true