name: Update SOFA Feeds

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Python with uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      
      - name: Backup existing data
        run: |
          echo "Creating backup of existing data..."
          if [ -d "data/feeds" ]; then
            cp -r data/feeds data/feeds.backup
            echo "✅ Backed up feeds directory"
          fi
          if [ -d "data/resources" ]; then
            cp -r data/resources data/resources.backup
            echo "✅ Backed up resources directory"
          fi
      
      - name: Setup binaries for Linux
        run: |
          echo "Setting up binaries for Linux environment..."
          
          # Check system architecture
          echo "System architecture: $(uname -m)"
          
          # Make binaries executable
          chmod +x bin-linux/sofa-gather bin-linux/sofa-fetch bin-linux/sofa-build bin-linux/sofa-cve
          
          # Verify binaries
          echo "Binary information:"
          file bin-linux/sofa-gather
          file bin-linux/sofa-fetch
          file bin-linux/sofa-build
          file bin-linux/sofa-cve
          
          # Test if they can run (basic check)
          ./bin-linux/sofa-gather --help || echo "sofa-gather test run"
          
      - name: Run SOFA Pipeline
        run: |
          echo "Running SOFA pipeline to update all feeds and resources..."
          
          # Show current directory and structure
          pwd
          ls -la bin-linux/
          
          # Run from repository root, not from scripts directory
          chmod +x scripts/sofa_pipeline.py
          
          # Run the pipeline from the root directory where bin-linux/ is located
          uv run scripts/sofa_pipeline.py run || {
            echo "⚠️ Pipeline failed, restoring backup..."
            [ -d "data/feeds.backup" ] && rm -rf data/feeds && mv data/feeds.backup data/feeds
            [ -d "data/resources.backup" ] && rm -rf data/resources && mv data/resources.backup data/resources
            exit 1
          }
      
      - name: Cleanup backups
        if: success()
        run: |
          rm -rf data/feeds.backup data/resources.backup
          echo "✅ Removed backup files after successful run"
      
      - name: Check and commit changes
        run: |
          git config user.name "SOFA Bot"
          git config user.email "sofa-bot@users.noreply.github.com"
          
          # Show what files changed
          echo "Files modified by pipeline:"
          git status --porcelain data/
          
          # Add specific directories that pipeline updates
          # This ensures we only commit what the pipeline actually modified
          git add data/feeds/v1/*.json 2>/dev/null || true
          git add data/feeds/v2/*.json 2>/dev/null || true
          git add data/resources/*.json 2>/dev/null || true
          git add data/resources/*.ndjson 2>/dev/null || true
          git add data/cache/index_metadata/*.ndjson 2>/dev/null || true
          git add data/cache/*.json 2>/dev/null || true
          
          # DON'T add HTML cache files to avoid bloat
          # git add data/cache/html/ - INTENTIONALLY NOT ADDED
          
          if ! git diff --cached --quiet; then
            # Show what will be committed
            echo "Files to be committed:"
            git diff --cached --name-only
            
            # Create detailed commit message
            TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
            git commit -m "Update SOFA feeds and resources [$TIMESTAMP]" \
              -m "" \
              -m "Automated update via GitHub Actions" \
              -m "- Updated feed data in data/feeds/v1/ and data/feeds/v2/" \
              -m "- Updated resources in data/resources/" \
              -m "- Updated cache metadata" \
              -m "" \
              -m "Note: HTML cache files are not committed to avoid repository bloat"
            
            git push
            echo "✅ Changes committed and pushed"
          else
            echo "ℹ️ No changes detected in feed/resource files"
          fi